spring:
  datasource:
    url: jdbc:mysql://bungee-db-dev-01.ccd5h24epdix.ap-northeast-2.rds.amazonaws.com:3306/bungee?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: bungee
    password: bungeeapi
    data-username: bungee
    data-password: bungeeapi
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 엔티티에 변화가 생겼을 때 테이블 스키마도 업데이트한다
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  resources:
    static-locations:
  servlet:
    multipart:
      max-file-size: 20MB

bungee:
  file-upload:
    default-dir: /bungee

server:
  port: 80